version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "maven"
    directory: "/bot"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
